# .github/workflows/docs.yml

on:
    push:
      paths:
        - docs/**
        - mkdocs.yml
  
    workflow_dispatch:
  
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
  
        - name: Set Up Python
          uses: actions/setup-python@v4
  
        # Install MkDocs, other dependencies, and do whatever else you need to do, then...
  
        - name: Build
          run: mkdocs build
  
        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: site
            path: site
  
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download Artifact
          uses: actions/download-artifact@v3
          with:
            name: site
            path: site
  
        - name: Deploy to Vercel
          uses: npx vercel --yes --cwd site --token ${{ secrets.VERCEL_TOKEN }} 
          env:
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  